### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by danielgomezrico** [gitote/gitote#2]
When I open https://gitote.com/ it return 404.

Thats normal? the service is shutdown?

**Comment by CodeMouse92** [comment]
It's still down, including on this end. It first complains about network protocol violations, and then it 404s upon refresh. Here's the full text of the error message I'm receiving. I have to say, this is very disappointing, as I was using Gitote for a project, and now my issues are inaccessible.

>Corrupted Content Error
>
> The site at https://gitote.in/ has experienced a network protocol violation that cannot be repaired.
>
> The page you are trying to view cannot be shown because an error in the data transmission was detected.
>
> Please contact the website owners to inform them of this problem.

**Comment by CodeMouse92** [comment]
The Gitote service was [officially shut down](https://gitlab.com/gitote/gitote/issues/4). The project runner claims he posted a notice on the site.
