### ISSUE TITLE
the website is down

### ISSUE THREAD

**Issue by ghost** [gitote/gitote#3]
### New Issue Checklist

- [x] I searched for [existing GitHub issues](https://github.com/gitote/gitote/issues)

### Issue Description

the website is down

**Comment by mittalyashu** [comment]
Seems like, the owner of this project is no longer working on this project.

**Comment by ghost** [comment]
@mittalyashu 
he switched to gitlab, and deleted the github profile (@yoginth)
apparently after microsoft announced github as part of them? :man_shrugging:

new repo: https://gitlab.com/gitote/gitote

**Comment by ghost** [comment]
also the site is down b/c it was deliberately shutdown: https://gitlab.com/gitote/gitote/issues/4

so this im closing the issue

**Comment by mittalyashu** [comment]
Oh! I see.
